#!/usr/bin/env python3
"""Smoke test hosted NVIDIA multimodal endpoints used by InsightPulse."""
from __future__ import annotations

import argparse
import base64
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def _default_test_image() -> Path:
    """Use a local screenshot/image asset to avoid brittle public image URLs."""
    assets = Path("/Users/rmtariq/.cursor/projects/Users-rmtariq-Documents-InsightPulse/assets")
    if assets.exists():
        images = sorted(assets.glob("*.png"), key=lambda p: p.stat().st_mtime, reverse=True)
        if images:
            return images[0]
    raise FileNotFoundError("No local PNG test image found. Pass --image /path/to/image.png")


def main() -> int:
    load_env_file(ROOT / ".env")
    load_env_file(ROOT / ".env.nemotron")

    # Import after env is loaded because multimodal_router resolves endpoint
    # defaults from NIM_LLM_BASE_URL/NIM_OCR_URL at import time.
    from scripts.multimodal_router import process_image  # noqa: WPS433

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--image",
        default=None,
        help="Public image URL or local image path to test OCR/vision routing",
    )
    parser.add_argument("--list-models", action="store_true", help="List likely hosted multimodal model IDs")
    args = parser.parse_args()

    if not (os.getenv("NIM_LLM_API_KEY") or os.getenv("NVIDIA_API_KEY")):
        print("❌ Missing NVIDIA_API_KEY/NIM_LLM_API_KEY in .env")
        return 2

    if args.list_models:
        from openai import OpenAI  # noqa: WPS433

        client = OpenAI(
            base_url=os.getenv("NIM_LLM_BASE_URL", "https://integrate.api.nvidia.com/v1"),
            api_key=os.getenv("NIM_LLM_API_KEY") or os.getenv("NVIDIA_API_KEY"),
        )
        terms = ("ocr", "vision", "vl", "omni", "asr", "audio", "parakeet", "embed")
        print("Candidate multimodal models:")
        for model in client.models.list().data:
            mid = getattr(model, "id", "")
            if any(term in mid.lower() for term in terms):
                print(f"  - {mid}")
        return 0

    image = args.image or str(_default_test_image())
    print(f"Testing image/OCR route with: {image}")
    text = process_image(image)
    print("\n✅ Multimodal image route OK\n")
    print(text[:2000])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


def _default_test_image() -> Path:
    """Create a tiny local PNG with visible text for hosted vision tests."""
    out = ROOT / "tmp" / "nemotron_multimodal_test.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        return out

    # 640x240 PNG containing: "PRN N9 TEST / Kos hidup / Nilai"
    # Generated once and embedded to avoid brittle public image URLs.
    png_b64 = (
        "iVBORw0KGgoAAAANSUhEUgAAAoAAAADwCAIAAAD0K1LUAAAFNklEQVR4nO3cMW7bQBRF0Q2n"
        "yP5L1hG4QJj1Z3MLJQyU9Y1dDkQwXqX2lQ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABg3i7v9wDg0m8AAH8gAAQIECBAYIABIECAAAGBAQaA"
        "AAECBAgQMMAAECBAgAABgwEGAACBAgQIGAAABAgQIEAAAYMBAgAAQIECBAwAACIECAAAED"
        "BAwGCAAAAgQIEDAAAAgQIECAgAEGgAABAgQIEDDAAAAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAg"
        "QIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAAB"
        "AgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgA"
        "ABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMM"
        "gAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQ"
        "MMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAA"
        "AQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQI"
        "AAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAg"
        "QIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAAB"
        "AgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAA"
        "ABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGG"
        "AAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQIGGAAABAgQIAAAQMMgAABAgQI"
        "GGA="
    )
    out.write_bytes(base64.b64decode(png_b64))
    return out
